/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as YoutubeRouteImport } from './routes/youtube'
import { Route as TwitterRouteImport } from './routes/twitter'
import { Route as LinkedinRouteImport } from './routes/linkedin'
import { Route as InstagramRouteImport } from './routes/instagram'
import { Route as FacebookRouteImport } from './routes/facebook'
import { Route as IndexRouteImport } from './routes/index'

const YoutubeRoute = YoutubeRouteImport.update({
  id: '/youtube',
  path: '/youtube',
  getParentRoute: () => rootRouteImport,
} as any)
const TwitterRoute = TwitterRouteImport.update({
  id: '/twitter',
  path: '/twitter',
  getParentRoute: () => rootRouteImport,
} as any)
const LinkedinRoute = LinkedinRouteImport.update({
  id: '/linkedin',
  path: '/linkedin',
  getParentRoute: () => rootRouteImport,
} as any)
const InstagramRoute = InstagramRouteImport.update({
  id: '/instagram',
  path: '/instagram',
  getParentRoute: () => rootRouteImport,
} as any)
const FacebookRoute = FacebookRouteImport.update({
  id: '/facebook',
  path: '/facebook',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/facebook': typeof FacebookRoute
  '/instagram': typeof InstagramRoute
  '/linkedin': typeof LinkedinRoute
  '/twitter': typeof TwitterRoute
  '/youtube': typeof YoutubeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/facebook': typeof FacebookRoute
  '/instagram': typeof InstagramRoute
  '/linkedin': typeof LinkedinRoute
  '/twitter': typeof TwitterRoute
  '/youtube': typeof YoutubeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/facebook': typeof FacebookRoute
  '/instagram': typeof InstagramRoute
  '/linkedin': typeof LinkedinRoute
  '/twitter': typeof TwitterRoute
  '/youtube': typeof YoutubeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/facebook'
    | '/instagram'
    | '/linkedin'
    | '/twitter'
    | '/youtube'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/facebook' | '/instagram' | '/linkedin' | '/twitter' | '/youtube'
  id:
    | '__root__'
    | '/'
    | '/facebook'
    | '/instagram'
    | '/linkedin'
    | '/twitter'
    | '/youtube'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FacebookRoute: typeof FacebookRoute
  InstagramRoute: typeof InstagramRoute
  LinkedinRoute: typeof LinkedinRoute
  TwitterRoute: typeof TwitterRoute
  YoutubeRoute: typeof YoutubeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/youtube': {
      id: '/youtube'
      path: '/youtube'
      fullPath: '/youtube'
      preLoaderRoute: typeof YoutubeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/twitter': {
      id: '/twitter'
      path: '/twitter'
      fullPath: '/twitter'
      preLoaderRoute: typeof TwitterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/linkedin': {
      id: '/linkedin'
      path: '/linkedin'
      fullPath: '/linkedin'
      preLoaderRoute: typeof LinkedinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instagram': {
      id: '/instagram'
      path: '/instagram'
      fullPath: '/instagram'
      preLoaderRoute: typeof InstagramRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/facebook': {
      id: '/facebook'
      path: '/facebook'
      fullPath: '/facebook'
      preLoaderRoute: typeof FacebookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FacebookRoute: FacebookRoute,
  InstagramRoute: InstagramRoute,
  LinkedinRoute: LinkedinRoute,
  TwitterRoute: TwitterRoute,
  YoutubeRoute: YoutubeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
